### ISSUE TITLE
Prevent duplicate address and subunit creation

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#101]
In the old version of Master Address, we checked, during address creation, that the new address wasn't duplicating a previous address.  This was part of the Address::validate() code.  There was also a database constraint preventing this as well.

We need to add in this duplicate address check into all Address actions that involve changes to the street_number.

Address
- [x] Add
- [x] Correct
- [x] Readdress
- [x] Renumber

Subunits
- [x] Add
- [x] Correct

**Comment by laurahaley** [comment]
Can we also add a unique constraint for subunits between the address_id, type_id and identifier?

**Comment by inghamn** [comment]
Yes, that should be no problem

**Comment by inghamn** [comment]
So, it turns out the naive unique constrain we added is not enough.  In postgres, null does not equal anything, including other nulls.  So our single unique constraint is not enough.
```sql
unique(street_id, street_number_prefix, street_number, street_number_suffix)
```
Two addresses can be added that have the same street_id and street_number, but have null for prefix and suffix.  Because null does not equal null, the unique constraint is satisfied (according to postgres).

We'll need to create multiple unique constraints, taking into account the possible null values for prefix and suffix.
