### ISSUE TITLE
Add search by location_id

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#107]
Other systems often relate to master_address through the location_id. It would be nice to have  a set search query by location_id like there is with address and street.  It would help with trouble shooting address issues. It would be fine to limit those to people who are logged in.  This may be related to issue #11

**Comment by inghamn** [comment]
I'm think we want a whole locations search, search results, and view for looking at stuff by location.  (As opposed to by address).  This would also address the discrepancy we have with external applications wanting "addresses" - by which they really mean streetAddresses including sububnits as separate "addresses" (which equates to "location" in master address.

**Comment by laurahaley** [comment]
Not exactly what you had in mind by a full location search, but simple
location_id search on the interface that is at the top with the address and
street search would be really helpful.

**Comment by inghamn** [comment]
Since there's no display of locations by location_id, I wasn't sure what the location_id search results would display.

I'm thinking of creating a /locations route for this.

**Comment by laurahaley** [comment]
It could produce a results list of hyperlinked "addresses" that are linked
to that location id.  As you say, these would be either addresses or
subunits. And it would be possible to have more than one result. Clicking
on the address record, would take you to the address or subunit screen for
that record.

For example , search for 41484 could give two records.

enityid - Address  - Active - Status - Location Use
31104 - 2509 E Ceadrwoood CIR - Active - Current - RS
29635 - 3420 S Claybridge DR - N  - Retired - RS






Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
I still need to add Jurisdiction and Sanitation to the response
