### ISSUE TITLE
Display location status

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#108]
Locations have a status, seperate from address and subunits, but we never display it.  It's important that we show all the information we have.

**Comment by inghamn** [comment]
#111

**Comment by laurahaley** [comment]
You did add display of locations status next to the location id. Not all
status appear because of issue #46

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
