### ISSUE TITLE
Add action note and update activity report for logged in users

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#113]
The activity report that used for address sharing in the past also contains the action notes. This column should only appear when the user is logged in.

It would also be nice to tack on concatenation of the street name and full address. Depending on what I'm doing the report for, I sometimes have to do this. The full address does not need to include the city state and zip.

This is my preference for the order of the columns in the report:

location_id
entity id
address type
action_date
person
street number
direction
street name
suffix
post direction
subunit
zip
action
location_type
action notes
full street name
full address

Thanks!

**Comment by laurahaley** [comment]
The activity report that used for address sharing in the past also contains the action notes. This column should only appear when the user is logged in.

It would also be nice to tack on concatenation of the street name and full address. Depending on what I'm doing the report for, I sometimes have to do this. The full address does not need to include the city state and zip.

This is my preference for the order of the columns in the report:

location_id
entity id
address type
action_date
person
street number
direction
street name
suffix
post direction
subunit
zip
action
location_type
action notes
full street name
full address

Thanks!

**Comment by laurahaley** [comment]
Paul's monthly address report doesn't include the action notes which makes it difficult for people to follow when they don't attend the monthly meetings. Action notes were part of reports in the old system.  There is a new addressing person who started and it would be great if we can get the activity report updated to what I've listed above or at least to include the action note field.

**Comment by laurahaley** [comment]
Mike Stewart asked if it was possible to add an "Old Address" column for when a street name is readdressed. He has to add that manually as well. I said I would pass it on.
Thanks

**Comment by inghamn** [comment]
Showing the "Old Address" for the street name changes will require a seperate custom report.   I can add that as an issue so we don't forget about this idea.
