### ISSUE TITLE
Add Additional Address to existing location action missing

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#123]
When two addresses are corner lot addresses, we add the first new address, then we add the second address to the same location id record as the first address. This button was called Add Additional Address on the old version and was above the location info. It is missing from this version of master address. We now have to add both addresses individually and then go into the database and update and delete the unneeded 2nd location related records manually.

![image](https://user-images.githubusercontent.com/15268633/82569655-8a674700-9b4e-11ea-84e1-9cabe3f702fd.png)

**Comment by inghamn** [comment]
We want to have a different label on the button that links to Address::add.  There might be some confusion with a "New Address" button here as well as on the street view.

**Comment by laurahaley** [comment]
Its okay with me if you don't hide it but I suppose there could be additional actions for locations added in the future and the description of what it does is helpful.
