### ISSUE TITLE
Add location_id, address_id, subunit_id to Activity Reports

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#14]
It would be helpful for our address cleanup effort related to sanitation if the location_id, address_id, subunit_id, could be added to the address related Activity Reports. It would be best to appear between Notes, and StreetID column

**Comment by inghamn** [comment]
I will add the location_id and subunit_id to the downloadable versions.  I won't try and squeeze any more information into the HTML version.

**Comment by laurahaley** [comment]
Sorry, I didn't look closer at your earlier comment, Can we have street_address_id too in between, location_id and subunit_id?
