### ISSUE TITLE
Retiring corner lot address also retires location when there is still another current address tied to that location

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#144]
I was switching the active address on a corner lot. https://bloomington.in.gov/master_address/addresses/42840.  I then needed to retire the other address that is not going to be used.  https://bloomington.in.gov/master_address/addresses/42839.  This set the status of the location id shared between the two (51965) to retired.

The default behavior should not be to retire the location if there is still a current address linked to that same location.

It would also be good if the coordinates for the address can also so be switched so we don't need to remap it.

The previous version of master address prompted the user when switching the active address if they wanted to retire the other current addresses on the same location.  This doesn't have to happen, but it would be nice.  I can provide more info or add this as another issue if you want to also make this change.

**Comment by inghamn** [comment]
When changing the status of an address_id, that address_id can be associated with multiple location_id's.  Additionally, each of those location_id's can have additional addresses associated with it.

We need to make a choice for each individual location_id associated with the address_id that is changing.

**Comment by inghamn** [comment]
We think the system will be better off if we drop the location_status altogether.  The real status that matters is the address_status and subunit_status.  We'll need to update the address_locations view; but, for the most part, we can just stop using location_status.

**Comment by inghamn** [comment]
#147
