### ISSUE TITLE
Add Places to master_address interface

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#145]
adding the gis.places data in the master_address interface would be helpful to us to maintain the data more easily and allow users to see what we have.  There are places that don't have an address (landmarks), where we would need a separate screen similar to People and Plats

**Comment by inghamn** [comment]
The place schema includes several tables.

* categories            
* place_alt_name_hist    
* place_alt_names        
* place_history          
* place_point_of_interest
* places                
* point_of_interest_types
* public_entities 
We don't need the place_point_of interest or the point_of_interest_type tables included

Places should have a link in the menu bar, like People and Plats.
The places, and place_alt_names should be editable through the interface. 

The categories and public_entities tables are lookup tables for the main place table.  They are pretty much set, so we could edit those in the database if needed.  

The place_history and place_alt_name_hist are just for display.

Not every place has an address.  For places that have an address, we should show the place information on the Address::View screen. 

Some places are considered Landmarks ( landmark_flag = 'Y)

**Comment by laurahaley** [comment]
I'm open to a priority staged approach in order of what would be most helpful to us maintaining that data and others viewing it.

1. Places that have addresses viewable on the related address screen.
2.  Ability to search places through the interface.
3. The ability to add and edit Places that have address (main place table only)
4. The ability to add and edit Landmarks (non addressed places).
5. The ability to add and edit Place aliases
6. The ability to add and edit categories, and public_entities.

At some point we are going to add a look up table for place_types
