### ISSUE TITLE
Address readdress action update

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#15]
Would like to also be able to have the option to  change address_type, location_use_type, mailable, and livable values when readdressing.   The existing values should stay as they are with the retiring address.
If  any of the required township, section, or zip code are null in the existing address,  an error happens when trying to readdress. It would be nice to be able set these too if they are null so the readdressing can happen in one action. Otherwise, you have to update the address first to set the township, section, and/or zipcode, then readdress it.

**Comment by inghamn** [comment]
I am planning on making the form so that you can change any and all information on the address during the Readdress action.  Does this sound like what you want; or, should we limit the editable fields to only a chosen few?

**Comment by inghamn** [comment]
What should happen to subunits on addresses that are readdressed?

**Comment by laurahaley** [comment]
can we have a choice.

1. Readdress Subunits (Default) - Subunit address changes to the new
address (subunit address id is updated to new address id for each unit)
2. Retire Subunits - (keep the current address id that is there but change
the sub unit and sub unit location statuses like you were retiring a unit
through the normal process)

While it is possible that some units go with the new address and some units
are retired, that seems complicated for the interface and there is a chance
that the user might not do it anyway.  So in this case, I think that they
should just use the default change with the address, then retire the units
that need retiring through that process.

I don't think that there is enough benefit to keeping the previous related
address id associated with the subunit that was changed to warrant the
complexity.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Updates #8

**Comment by inghamn** [comment]
Updates #2
