### ISSUE TITLE
Permission error when adding and updating places

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#150]
This error appeared when trying to update or add a new place through the interface.
SQLSTATE[42501]: Insufficient privilege: 7 ERROR: permission denied for relation places

**Comment by inghamn** [comment]
This looks like just a permission granting problem.  The Master Address user must not have insert/update permissions for places.

**Comment by inghamn** [comment]
I granted Master Address permission for all tables in the place schema.
