### ISSUE TITLE
Change active address location bug

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#17]
For an address location that has 2 current addresses (corner lot) and one of the addresses has 2 locations, one retired.  When switching the active address for the current location, the data gets updated correctly, but the interface does not show either of the addresses active.  There are two locations associated with one of the addresses because it was moved from another location to identify it as a corner lot location.  Also when selecting the address, the view address screen defaults to the Retired address location and not the current address location. the view address screen for the other address shows the active flag correctly.

Here are the particulars
https://apps.bloomington.in.gov/master_address/addresses/viewAddress.php?address_id=23328
Address is 1202 N Enterprise DR street address id 23328, current location id 35217.  Move active flag from 3130 W Venture Blvd street address id 23325.

**Comment by inghamn** [comment]
Here is the address in the new system:
