### ISSUE TITLE
Change of address transfer data flow

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#2]
on Readdress action action for address editing, all the data with the address record except for the elements that are editable on the change of address screen should be copied to the new address.  Some fields translate, but some don't. I expect only the required fields are transferred. The ones I notice are the coordinates. We have to re-map the new address. This may need to happen, but by default it would be nice not to have to re-map.  Also helpful to add address type, jurisdiction, plat and lot number to the elements that can be edited when changing an address.

**Comment by laurahaley** [comment]
Null values in township or section in the original address produces an error message if the address is not updated first. It would be nice to it be one step by also adding township and section as elements that can be edited when changing the address

**Comment by inghamn** [comment]
When readressing, the new address starts with a copy of all the data from the original address.
