### ISSUE TITLE
Bulk subunit entry

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#22]
As more and bigger apartment complexes are going up, the number of subunits entered at one time is increasing.  The old application only allowed for a few subunits to be batch-entered at a time (because of character limits).

We should look at doing a more formal bulk entry method.  Possibly something like having the engineer download a spreadsheet to fill out.  And supporting a CSV import (with predefined fields).

**Comment by laurahaley** [comment]
upload spreadsheet could look like this.  If this could be done without the interface by having a script run by an administrator such as myself, that would work as a stop gap.
[samplebulksubunitsheet.xlsx](https://github.com/City-of-Bloomington/master_address/files/4800973/samplebulksubunitsheet.xlsx)
