### ISSUE TITLE
Move search from home page to banner

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#3]
The basic Search tool located on the home page would be helpful on other screens.  perhaps moving it to the banner would solve

**Comment by inghamn** [comment]
https://github.com/City-of-Bloomington/master_address/issues/44#issuecomment-448594345

**Comment by inghamn** [comment]
There are several basic searches in the new system: one for each type of thing (address, street, subunit, plat, etc.)  The one on the home screen only searches through addresses.

https://aoi.bloomington.in.gov/master_address

Do we want just that search in the banner, or should we add multiple search boxes up top?
