### ISSUE TITLE
Street Seach improvements

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#4]
From Russ -  The generated pick list often requires scrolling, which has to be done by using the mouse (moving a hand from the keyboard to the mouse). Sometimes I select a street name from the pick list and then nothing is returned for the search, which doesn't make sense. It also requires a mouse click to search for string segment, otherwise it selects the first hit from the pick list. Also, selecting a street name from the pick list only narrows the search to that one name. I then have to click on that name to bring up the record. It would be nice to have the street come up after selecting the name from the pick list.

**Comment by inghamn** [comment]
I've currently eliminated the autocomplete drop down on search fields.  The confusion stemmed from attempting to autocomplete a search query (not doing a search and showing dynamic results a la google.)

Does the search work better without the autocomplete?

**Comment by laurahaley** [comment]
For the street names, I think it works better without the autocomplete.
With the current street search, the list does not grow as you type so it
can often pick for you something other than what you are searching for.
Also, even when it gives you what you want, you still have to click to
select it from the list, then select it again to complete the search
anyway. I think the new way will eliminate some clicks.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
