### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#44]
The address parser is not 100% accurate on parsing; besides, there are cases where we want to do more nuanced searches.

We should provide an "Advanced Search" form with all the address parts split out into separate fields.

Should the form be on the same screen as the simple text string search?

**Comment by inghamn** [comment]
It would nice if we could tell it to search for a range of addresses on a street.  For example, be able to find all the addresses whose numbers are between 100 and 200.

**Comment by laurahaley** [comment]
I'd like to see a simple one line address and street search box on the top
of every screen if possible.  It not a big deal to go back to the home page
to do a search, but sometimes, I'm doing a lot of look ups and it would
save me some clicks to be able to search from the screen I'm on.  The way
it is now, there is clickable text to take me to the address or street
search page which is an improvement, but I still need to then fill in the
values..

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
