### ISSUE TITLE
Location purposes

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#45]
I still need to incorporate purposes into the new version.   Purposes are tied to locations.  So, for an address we'll need to show the purposes for each one of the locations related to the address.

**Comment by inghamn** [comment]
This is probably affecting people's expectactations of what is shown in MyCity

https://github.com/City-of-Bloomington/myCity/issues/11

**Comment by inghamn** [comment]
This needs to be added before we can update MyCity.

https://github.com/City-of-Bloomington/myCity/issues/7

**Comment by inghamn** [comment]
In the old version, Purposes were displayed as if they were part of the address, even though they were tied to locations.  The old query returns all purposes tied to any location associated with the address.  This is irrespective of location status or whether the address was the active address for a location.

Did I do this incorrectly back then, or is this, in fact, how purposes are intended to be associated with addresses?

**Comment by inghamn** [comment]
In the current interface, they're never displayed by location and they're never queried by location.  All the purposes for all the locations are lumped together in the address information.  You never know which purpose comes from which location for the address.

**Comment by laurahaley** [comment]
I see.  Then it should be associated with the location that is being viewed
somehow or the current location for that address. I suppose we could move
it that data to be associated with the address, but then we need to make
sure it travels with it when readdressed. And it would mean that we need to
do a bit more work to associate the sub unit with the location purpose.  I
can't seem to access the new interface at
https://dev.bloomington.in.gov/master_address/, I'm getting a 503

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
I've incorporated purposes into the version.  They're displayed as part of the address information, even though they're associated with the locations.  This is what the old system does.

There was never a way to edit them in the master address interface, so, perhaps, we can ignore any confusion this cases, for now.

**Comment by laurahaley** [comment]
Yes I think it is fine this way.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
