### ISSUE TITLE
Drop end_dates on all status tables

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#46]
The old technique for tracking status changes over time is not working so well in practice.  The old idea was to have a start and end date for each status.  However, this has proven to be confusing; and, it is just extra information to type.  The end date is not independent, it must always be the start date of the next row in chronological order.

We should drop all the end dates from the status tables, as they just cause confusion and provide room for errors.

**Comment by laurahaley** [comment]
Before the Master_Address app, we left the status as 1 and populated the
end date to retire addresses. We did not add a new row with a status of 3.
So for sll those records, part of the migration will need to be to add a
row with the status of 3 and the start data populated with the end date.
Hope that make sense.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
It looks like all the end dates for statuses that overlap are withing 24 hours of the start date.  So, dropping the end_date column should be okay, with no data changes to make.

```sql
select s.subunit_id, 
       max(s.start_date) - max(s.end_date) as diff
from subunit_status s
where s.subunit_id in (
    select distinct l.subunit_id
    from subunit_status l
    join subunit_status x on l.subunit_id=x.subunit_id and l.id != x.id
        and ((x.end_date is null or x.end_date >= l.start_date) and (l.end_date is null or l.end_date >= x.start_date))
)
group by s.subunit_id
```

**Comment by inghamn** [comment]
There many status records that incorrectly have just one status row with an end date set to the past.  This is saying that it has no status currently.  These would also have to be cleaned up by creating new rows, making the old end_date the new start_date.

```sql
select l.*, s.records
from address_status l
join (
    select address_id, count(*) as records
    from address_status group by address_id) s on l.address_id = s.address_id
where end_date is not null and records = 1
```

**Comment by inghamn** [comment]
#111
