### ISSUE TITLE
Report system

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#49]
The old master address generated "report" queries using a complex form.   Filling out the form would result in a dynamically generated query that would return live results. (For addresses or streets)

The form, however, seems to have been confusing for users.  We should create a new reporting system that results in much fewer parameters per report.  It would probably be easier to maintain these report queries if they were plain text SQL queries.

**Comment by inghamn** [comment]
Reports should produce HTML results as well as allow for downloading results as CSV.

**Comment by laurahaley** [comment]
While there can be other canned report. The priority is a City Address
Activity Report where they will want

Fields:
Action Date
Full Street Number (concat of prefix, number, suffix)
Street Name Direction
Street Name
Street Suffix
Street Post Direction
Full Subunit (concat of type and identifier)
Zip Code
Action Name
Action Person
Address Type
Location Type Name
Action Notes

For Address or Subunit Actions
Add
Assigned
Readdressed
Reassigned
Retired
Corrected
Updated

And Gov Jurisdiction = Bloomington

And Action Date is between  date 1 and date 2.  Date 2 could default to the
current date and for date 1 they would enter (we could default to the first
of the previous month or 30 days prior)

Thanks



Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
So, in 5b897d292c10f0e2738834f238b3145aa778bbef I've implmented the start of a reporting system.  In this system, reports are plain text SQL files with a PHP class to describe and execute them.  They are dropped into the a directory inside the site's data directory (as opposed to included as source code)

This seems to acheive the results of limiting the parameters on the individual report forms, as well as simplifying the creation of custom reports.

Pagination and sorting are not implemented, yet, but probably could be with another day of work.

One thing I really don't know how to do would be to put links on individual rows of the output.  The reporting system does not know what the output is, so it cannot draw links to the *things* in the system the output references.  With this approach, I don't know if I can solve the linking problem, or not.

**Comment by charlesbrandt** [comment]
Even if the output was a text or csv format, you could include the URL to the publicly visible route in master address that references the corresponding resource. Many applications are smart enough to convert a text string that starts with 'https://' into a clickable link when displaying the field.

**Comment by laurahaley** [comment]
I got this error when using the output to csv button


Fatal error: Uncaught TypeError: array_keys() expects parameter 1 to be array

TypeError: array_keys() expects parameter 1 to be array

Call Stack:
    0.0000     417736   1. {main}() /home/inghamn/Documents/Projects/MasterAddress/master_address/public/index.php:0
    0.1208     806440   2. Application\Reports\Views\ReportView->render() /home/inghamn/Documents/Projects/MasterAddress/master_address/public/index.php:46
    0.1208     823216   3. include('/home/inghamn/Documents/Projects/MasterAddress/master_address/templates/csv/default.inc') /home/inghamn/Documents/Projects/MasterAddress/master_address/src/Application/Template.php:97
    0.1208     823448   4. Application\Reports\Views\ReportView->includeBlocks() /home/inghamn/Documents/Projects/MasterAddress/master_address/templates/csv/default.inc:10
    0.1208     839960   5. Application\Block->render() /home/inghamn/Documents/Projects/MasterAddress/master_address/src/Application/Template.php:166
    0.1209     856960   6. include('/home/inghamn/Documents/Projects/MasterAddress/master_address/blocks/csv/reports/output.inc') /home/inghamn/Documents/Projects/MasterAddress/master_address/src/Application/Block.php:75
    0.1209     856960   7. array_keys() /home/inghamn/Documents/Projects/MasterAddress/master_address/blocks/csv/reports/output.inc:9
