### ISSUE TITLE
Add person contact type of "Other"

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#58]

**Comment by laurahaley** [comment]
I'm thinking about changing the Property Owner type to be just "Public" and
not having to add an Other field.  The type of contact can vary for each
instance it applies.  For example, Joe Smith could be a property owner
requesting a change of address but also points out that his neighbors
address is out of sequence. He is the property owner of the first address,
but not the second.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
That seems reasonable. 

For reference, here are the current contact types:
gis=# select distinct contact_type from people order by contact_type;
    contact_type     
---------------------
 Address Coordinator
 CBU
 Developer
 E911 Administrator
 Emergency Services
 GIS
 Government Agency
 Property Owner
 Utility Provider

**Comment by inghamn** [comment]
I'm reviewing the data, and it looks like there's only one "Property Owner" contact.  It's Matt Press, and he's moved to Washington DC, now.

**Comment by laurahaley** [comment]
He was still the person involved with whatever the update was at the time
so he should remain. We aren't going to maintain the current contact
information for everyone in the contacts. If you have some ideas on how to
better store information on the people requesting or providing information
on an address, we can talk about it.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
