### ISSUE TITLE
Notes fields should have smaller textareas

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#61]
We want to encourage people to write more condensed comments on things when they're doing stuff.  Also, the textareas being rendered right now take up a lot of space.

The textareas all need to take up less space; maybe only two lines tall.

**Comment by laurahaley** [comment]
Can they also be labeled Address Notes and Change Notes

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Sure, I'll go ahead and label them that way.
