### ISSUE TITLE
Update designation error

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#66]
Argument 3 passed to Domain\Streets\Designations\UseCases\Update\UpdateRequest::__construct() must be an instance of DateTime, null given, called in /srv/sites/master_address/src/Application/Streets/Designations/Controller.php on line 51

**Comment by inghamn** [comment]
This is happening on street names that did not have a start_date in the old Oracle data.

I think it might be worth setting all the null start_dates to some date in the distant past.

**Comment by laurahaley** [comment]
We used 1/1/2000 as the default date for addresses. We can use that for
streets as well. Let me know if you want me to do that.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
1/1/2000 is fine with me.  Should I do this as part of the data migration?

```sql
update street_designations set start_date='2000-01-01' where start_date is null;
```

**Comment by laurahaley** [comment]
Doing this at the migration would be fine with me.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Added start_dates for all designations during the migration.
