### ISSUE TITLE
Add address action should have "assign" option

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#67]
When doing the "Address Add" action, the form should ask whether it's adding an address to the system that was missing, or assigning a new address.

The old master address just had a radio button for this, but did not explain what each of the options meant.  We'll need to have a human readable description for each option.  Ultimately the chosen option should only affect the action name that gets saved in the changeLog.

**Comment by laurahaley** [comment]
We can use "Add missing address" for the add action and "Assign new
address" for the assign action

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
