### ISSUE TITLE
Intersections

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#7]
There is a database of intersections that could be integrated into master address. We could then also use these to support intersections in uReport

**Comment by laurahaley** [comment]
Sounds good if you want to access and view the information. The intersection tables should be part of the road/street database and not the address database as far as schema go.

**Comment by inghamn** [comment]
Intersections were added to the Master Address web application in Oct 2015, in order to support inRoads.  The implementation reads from haleyl.intersection_segments in Oracle.

e0757e6d6707818e93fcc77b8cbc9598492cf3ac
be9ff36842e9228c9c4477f2e8b5f1d872a320ec

**Comment by inghamn** [comment]
It doesn't make sense to write a seperate application just for looking up intersections.

Intersections make sense as part of the master address interface.  In fact, in order to look up intersections, you necessarily need to search and join on address tables - in this case, streets, designations, and streetNames.  Intersections without address information (ie. street names) are just a bunch of ID numbers.

**Comment by laurahaley** [comment]
I'm not sure what the intersection data will look like when we bring it
into arcgis. So I wouldn't spend much time on this now.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Pre-req for 
https://github.com/City-of-Bloomington/inRoads/issues/194
