### ISSUE TITLE
zip code entry should populate postal city

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#78]
When choosing from the zip code list when entering a new address, the postal city does not get populated as it does on the current app.  It would be best if the zip code choice controlled the postal city even to the point that it was not editable through the interface.

**Comment by inghamn** [comment]
I see that there is a zip_codes table with the cooresponding cities.  Should we only populate the zip code drop with values from this table?

Currently we populate the zip code choices by select distinct zip code from all addresses in the system.  This results in a much longer list of zip codes.

https://github.com/City-of-Bloomington/master_address/blob/240bdf82435010749b7ff4b041bc52d7060b50e4/src/Domain/Addresses/DataStorage/PdoAddressesRepository.php#L564

**Comment by laurahaley** [comment]
I think we should populate zip code from the zip code table.  It looks to
me that that the zip codes in the addresses table and the zip code table
are the same except the 619 records where the zip code is null.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Would it make sense to drop the city, state fields from the addresses table, and always join to the zip codes to get the city state?  I know we still need to write some views for convenience.

**Comment by laurahaley** [comment]
I think that should be something we look into.  Can put put it in the next
revision?

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by laurahaley** [comment]
Can we still auto populate the Postal City this version?

**Comment by inghamn** [comment]
I've moved the database changes over to a seperate issue #95 

This issue will just focus on some javascript to populate the city field automatically when a user changes the zip code on an address form.
