### ISSUE TITLE
Address: update action

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#79]
The update action is missing from the actions available for addresses.  There is a difference between the correct and update action for address.  The correct action is involves "correcting" the actual address elements, such as number, street name, zip code.  The update action involves making edits to the descriptive attributes of an address which is everything else - such as the township, section,  plat, lot, location information,etc.  Notifications will be made about address corrections, but it is optional to report updates to outside agencies.

**Comment by inghamn** [comment]
Here are the fields that are left after filtering out the street, street number, and zip fields.  Are all of these okay to edit during an update action?

* address2       
* address_type   
* jurisdiction_id
* township_id    
* subdivision_id 
* plat_id        
* section        
* quarter_section
* plat_lot_number
* notes

**Comment by laurahaley** [comment]
Yes those are the fields. Can we also update location related info, use
type, mailable, and livable?

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
I need clarification on which rows in the location table to update.  When an address has multiple locations, do you want all the location rows for that address to be modified?

**Comment by inghamn** [comment]
I think we're wanting something like:
```sql
update locations set group_quarter=TRUE
from location_status
where address_id=10643
  and active
  and location_status.location_id=locations.location_id
  and start_date <= now() and (end_date is null or end_date >= now())
  and status='current'
```

**Comment by laurahaley** [comment]
Yes, I think that is it.

select al.*, als.*
    from address.locations al
        join address.location_status als on al.location_id = als.location_id
            where al.address_id = 28398
            and active
  and als.start_date <= now() and (als.end_date is null or als.end_date >=
now())
  and als.status='current'



(from the old data - I can't seem to copy and paste the results from
pgadmin)
LOCATION_ID LOCATION_TYPE_ID STREET_ADDRESS_ID SUBUNIT_ID MAILABLE_FLAG
LIVABLE_FLAG ACTIVE GROUP_QUARTER STATUS_CODE EFFECTIVE_START_DATE
LOCATION_ID_1 EFFECTIVE_END_DATE
*71195* *Property Parcel* *28398*
*no* *no* *Y*
*1* *9/19/2017* *71195*
34884 Property Parcel 28398
no no Y
3 3/12/2015 34884
34884 Property Parcel 28398
no no Y
1 1/1/2000 34884 3/12/2015 4:35:46 PM

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
