### ISSUE TITLE
Copy address information when readdressing

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#8]
Can coordinate fields associated with a address record follow to the new record when running readdressing action. The data will then be there and not have to wait for us to map the new address to the building record.

**Comment by laurahaley** [comment]
See issue #2 for more info on data that should transfer

**Comment by inghamn** [comment]
When readdressing, the new address starts with a copy of all information from the old address.

**Comment by inghamn** [comment]
With the latest updates we only copy fields that the Add Address Request supports.  When we removed lat/long from the Add Address Request, we stopped copying all the coordinate information.

We need to have the request support these fields without the user having to enter them.

**Comment by inghamn** [comment]
The PDOAddressRepository::Add must support setting the geometry fields, even if we do not display them in the form.  We can attempt to keep users from entering geometry data during Address::Add by not displaying those fields in the form.
