### ISSUE TITLE
address contact seach and label issue

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#80]
The search for an existing contact isn't working when creating a new address or readdressing an existing one.  I didn't realize that the chooser issue that we discussed with changing a street name an address is one applies to the contacts.   We need a way to apply an existing contact to the change_log. It's not a problem for us to add a new contact first if needed before running an address action.

Also in the address and streets main screen, there are two change log  fields labeled Contact/contact. The first one should be labeled User (the user who makes the change) and the second one should be contact.

**Comment by inghamn** [comment]
The relabelling of all People to Contacts in #68 was not precise enough.  We want to make a distinction sometimes between a user an a contact.  The labelling will need to accomodate this.

**Comment by inghamn** [comment]
> The search for an existing contact isn't working when creating a new address or readdressing an existing one.

I am not able to replicate this problem.  It is working for me.  The modal dialog to "Find Someone" comes up, I am able to fill it out, get back results,  and choose one of the results to populate the "Contact" field for the change log.

It is true that this modal dialog does not have a way to add a new Person/Contact/whatever.  I expect it to be required to add new contact people to the system before adding a bunch of addresses that are related to that contact person.  The modal dialog allows you to find and choose existing people.

**Comment by laurahaley** [comment]
It is working for me now. Thanks

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
