### ISSUE TITLE
Street Designations of type STREET should always be rank 1

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#84]
The change street name designation action is essentially changing the street name by adding a new street name to the designations for this street with the designation type = Street. The rank should always be 1 and the user shouldn't be able to change this here. Same with updating street designations, if the type is street, they can't change the rank. We could leave this second part until later.

**Comment by laurahaley** [comment]
The change street name designation action is essentially changing the street name by adding a new street name to the designations for this street with the designation type = Street. The rank should always be 1 and the user shouldn't be able to change this here.  Same with updating street designations, if the type is street, they can't change the rank.  We could leave this second part until later.

**Comment by inghamn** [comment]
Part of changing the street name involves setting the old STREET designation to HISTORIC.  Should that rank be modified; or should it remain as rank=1?

**Comment by inghamn** [comment]
When adding a street to the system, should we allow designations other than type STREET?

**Comment by laurahaley** [comment]
Ideally the Historic name rank would be set to 2 then any existing name designations would slide down 1 place

**Comment by laurahaley** [comment]
When adding a street, only allowing the designation Street will be enough I
think.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
