### ISSUE TITLE
Interface to edit  type on location

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#93]
Location use type editing is missing from the  Address update action so there is no way to update it. Location Use type is also not displayed on the address screen. There isn't a lot of room for it in the Location data grid but we need to be able to see it.

**Comment by laurahaley** [comment]
Sorry, I see where the location use type is now displayed as a code.  I forgot. There still isn't a way that I see to update the location use type.

**Comment by inghamn** [comment]
I did not build an admin interface for editing the location types, in the new version of Master Address.  They rarely changed.  In the meantime, they can be edited directly in the database.  The location types are in a simple lookup table "location_types".

It is safe to change the code, name, and description to whatever you like.  Throughout Master Address, only the ID is used.

**Comment by inghamn** [comment]
All of this also applies to the other "types" lookup tables.

* location_types
* street_types
* subunit_types
* street_designation_types

**Comment by laurahaley** [comment]
It is not the location use type itself I need to edit. I need to change the
location use type from an address to say Unknown to Single Family.  I don't
see a way to do it. You can change the location mailble, liviabl, and
group quarters flags, but not the use type.



Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
