### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#94]
We want to be able to deploy this application automatically when we publis a new version.  We are working on using docker containers.

**Comment by inghamn** [comment]
We're doing the docker build in our CI system.  We should remove the hard coded docker command from the Makefile.

**Comment by sethCOB** [comment]
I have created a task definition in Concourse that will seek out VERSION files and combine them with the latest commit hash during the build process. I have already applied the changes to the pipeline for Master Address, so images are now building with proper labels.

**Comment by inghamn** [comment]
We've decided to have all apache containers write their logs to a shared volume.  Each container should name their access and error logs using the hostname in the filename.

**Comment by inghamn** [comment]
We didn't account for the CORS headers in the Docker image

**Comment by inghamn** [comment]
Added CORS header at the proxy server level.  We probably do not want to do this in each individual container
