### ISSUE TITLE
Engineering users have no permissions

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#96]
We launched with Engineering users having the same permissions as the general public.  We should add in some permissions for them.

The old Master Address granted full permissions (do anything with)

* addresses
* streets
* subunits
* plats
* people
* reports

Do we just want to replicate these permissions in the new version?

**Comment by laurahaley** [comment]
Yes on the permissions. They are no longer Engineering, Paul is
transportation and Eric is planning. We call their job role address
coordinators.  Perhaps a role called cityaddress or cityaddressedit.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Here are the permissions we can now grant in Master Address:

### Addresses
* add
* activate
* changeStatus
* correct
* update
* readdress
* verify
    
### Subunits
* add
* activate
* changeStatus
* update
* verify
    
### Streets
* add
* alias
* update
* rename
* changeStatus
* renumber
    
### Street Names
* add
* correct
    
### Street Designations
* update
    
### Sanitation
* update
    
    
And then these things all have just a generic "update" action:

* people
* plats
* towns
* townships
* jurisdictions
* subdivisions

**Comment by inghamn** [comment]
For roles called "cityaddress" and "cityaddressedit", do we want to grant permission for all of these - or just some of them?

**Comment by laurahaley** [comment]
They should be granted permissions for all of them. We need just one role.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
If we're granting permission for all these things, do we need another role?  We already have the "GIS" role which has permission for all of these things.

**Comment by laurahaley** [comment]
Is this just a role within the master address app or within postgres? GIS
People will have permissions to do things with data in other postgres
databases that we don't want Eric and Paul to do. True there isn't a way
for them to easily get there now.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
This is just about the roles in the web interface for Master Address.

**Comment by laurahaley** [comment]
OK. Then they should have the same permissions. The role name GIS isn't
really accurate. but you can use it if you want. Not all GIS staff will
necessarily have permissions to this.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
We can rename the role to whatever you think makes sense.  Would something like "City Staff" or "Employee" make more sense?

**Comment by laurahaley** [comment]
I think that something like addressedit or cityaddressedit would be
better.  Not all employees or city staff should have editing rights.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
Okay, I will:
* delete the "Engineering" role
* rename the "GIS" role to "addressedit"
