### ISSUE TITLE
Street designations must have unique ranks

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#98]
Street designations for a street must each have a different rank.  

This is driven by the integration with our dispatch system.  We must provide police and fire with street name aliases in a strict order of preference.

There are several actions in the system that involve changing street designations.  We'll need to update each of them to account for the unique street_id, rank.  Then, we'll need to create a new action to allow reordering of all the aliases at once.

- [x] Street::Alias
- [x] Street::ChangeName
- [x] Street/Designation::Update
- [x] Street/Designation::Reorder

**Comment by laurahaley** [comment]
I added the constraint on the database.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
In order to account for the unique rank requirement, I'm thinking we should remove the rank field from the Alias, Change Name, and Update actions.  I think, instead, when doing these actions, we assign the rank automatically, behind the scenes.  I think it makes it easier and less confusing if we add an action just to reorder the ranks.

Street Designation::Reorder would show all of the names and ranks, and let the user rearrange the ranks. (Preserving the STREET designation as rank 1)

**Comment by laurahaley** [comment]
Alright with me. I think it will be apparent to the user what rank will be
assigned as long as they are paying attention.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
